package org.gym.workouts;

import org.gym.Workout;

public enum ShoulderWorkout implements Workout {
    SEATED_BB_BACK_MILITARY_PRESS,
    SEATED_BB_MILITARY_PRESS,
    ALT_MILITARY_DB_PRESS,
    INCLINED_DB_PRESS,





    STANDING_DB_LATERAL_RAISES,
    STANDING_DB_LATERAL_RAISES_ALT,
    STANDING_DB_LATERAL_RAISES_BACK,
    UPRIGHT_ROPE_ROWS,




    CABLE_REVERSE_FLIES,
    NEUTRAL_ROPE_FRONT_RAISES,
    SINGLE_CABLE_REVERSE_FLIES,
    SINGLE_ARM_LOW_PULLEY_FRONT_RAISES
}
