package org.gym.workouts;

import org.gym.Workout;

public enum TricepWorkout implements Workout {
    ROPE_PUSH_DOWNS_CLOSE_GRIP,
    BODY_WEIGHT_PUSH_DOWNS,
    SINGLE_ARM_PUSH_DOWNS,
    SINGLE_ARM_PUSH_DOWNS_UH,
    BB_PUSH_DOWNS,
    SINGLE_PUSH_DOWNS,



    BENCH_DIPS,
    KICK_BACKS_BENCH_SUPPORT,
    KICK_BACKS_BENCH_SUPPORT_SINGLE_ARM,
    SKULL_CRUSHERS,
    SKULL_CRUSHERS_DECLINED_BENCH,


    DECLINED_ALT_DB_EXT,
    DECLINED_DB_EXT,
    SINGLE_ARM_DB_EXT,
    DOUBLE_ARM_EXTENSION,
    OVER_HEAD_ROPE_EXT_75,
    OVER_HEAD_V_BAR_EXT

}
